version: '3.9'

services:
  registry:
    image: registry:2.8.1
    restart: unless-stopped
    ports:
      - '5000:5000'
    labels:
      # Enable Traefik
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      # Docker registry
      - 'traefik.http.routers.docker-registry.rule=Host(`${HOSTNAME}`)'
      - 'traefik.http.routers.docker-registry.entrypoints=https'
      - 'traefik.http.routers.docker-registry.tls=true'
      - 'traefik.http.routers.docker-registry.tls.certresolver=default'
      # Authentication
      - 'traefik.http.middlewares.docker-registry-auth.basicauth.users=${AUTH_USERS}'
      - 'traefik.http.routers.docker-registry.middlewares=docker-registry-auth'
    volumes:
      - docker-registry:/var/lib/registry
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  docker-registry:
